--- 
- 
  copy: "src=/tmp/{{ inventory_hostname }}/ca.crt dest=/etc/openvpn/ca.crt  mode=644 owner=root group=root"
  name: "Copying CA certificate"
- 
  copy: "src=/tmp/{{ inventory_hostname }}/{{ inventory_hostname }}.crt dest=/etc/openvpn/{{ inventory_hostname }}.crt mode=644 owner=root group=root"
  name: "Copying Client certificate"
- 
  copy: "src=/tmp/{{ inventory_hostname }}/{{ inventory_hostname }}.key dest=/etc/openvpn/{{ inventory_hostname }}.key  mode=600 owner=root group=root"
  name: "Copying Client key"

- name: "Copying client.conf to the OpenVPN client"
  template: src=client.conf.j2 dest=/etc/openvpn/client.conf
  notify: restart openvpn

- name: "Removing Cert Directory"
  local_action: "command rm -rf /tmp/{{ inventory_hostname }}"

