---
-
  hosts: ldap-server
  pre_tasks:
    - sysctl: name=kernel.hostname value={{ inventory_hostname }} state=present
      ignore_errors: yes
    - service: name=network state=restarted
      when: ansible_os_family == 'RedHat'
  roles:
    - etcHosts
    - easy-rsa-CA
    - easy-rsa-certificate
    - ldapserver
  sudo: true
  vars:
   - x509_ca_server: "{% for host in groups['ldap-server'] %}{{ hostvars[host]['ansible_fqdn'] }}{% endfor %}"
   - countryName: "AU"
   - reginalName: "Victoria"
   - cityName: "Melbourne"
   - organizationName: "Monash University"
   - emailAddress: "shahaan@gmail.com"
   - organizationUnit: "defaultUnit"
   - ldapDomain: "dc=monash,dc=edu,dc=au"
   - ldapManager: "cn=Manager,dc=monash,dc=edu,dc=au"
   - ldapBindDN: "cn=ldapuser,ou=users,dc=monash,dc=edu,dc=au"
   - ldapUserBase: "ou=users,dc=monash,dc=edu,dc=au"
   - ldapGroupBase: "ou=groups,dc=monash,dc=edu,dc=au"
   - ldapBase: "dc=monash,dc=edu,dc=au"
   - ldapURI: "{% for host in groups['ldap-server'] %}ldaps://{{ hostvars[host]['ansible_fqdn'] }}{% endfor %}"
   - smtp_smarthost: "{{ ansible_hostname }}"
   - ldapManagerPassword: "imldap"
   - ldapBindDNPassword: "imbinddn"
   - domain: ""
   - karaage_sql_password: "imkaraage"
   - mysql_root_password: "immysql"
   - x509_key_file: "/etc/ssl/private/server.key"
   - x509_cert_file: "/etc/ssl/certs/server.crt"
   - x509_cacert_file: "/etc/ssl/certs/ca.crt"
   - x509_csr_args: ""
   - x509_sign_args: "{{ x509_csr_args }}"
   - x509_common_name: "{{ inventory_hostname }}"
- 
  hosts: karaage-server
  pre_tasks:
    - sysctl: name=kernel.hostname value={{ inventory_hostname }} state=present
      ignore_errors: yes
    - service: name=network state=restarted
      when: ansible_os_family == 'RedHat'
  roles:
    - etcHosts
    - easy-rsa-certificate
    - karaage3.1.17
  sudo: true
  vars:
   - x509_ca_server: "{% for host in groups['ldap-server'] %}{{ hostvars[host]['ansible_fqdn'] }}{% endfor %}"
   - countryName: "AU"
   - reginalName: "Victoria"
   - cityName: "Melbourne"
   - organizationName: "Monash University"
   - emailAddress: "shahaan@gmail.com"
   - organizationUnit: "defaultUnit"
   - ldapDomain: "dc=monash,dc=edu,dc=au"
   - ldapManager: "cn=Manager,dc=monash,dc=edu,dc=au"
   - ldapBindDN: "cn=ldapuser,ou=users,dc=monash,dc=edu,dc=au"
   - ldapUserBase: "ou=users,dc=monash,dc=edu,dc=au"
   - ldapGroupBase: "ou=groups,dc=monash,dc=edu,dc=au"
   - ldapBase: "dc=monash,dc=edu,dc=au"
   - ldapURI: "{% for host in groups['ldap-server'] %}ldaps://{{ hostvars[host]['ansible_fqdn'] }}{% endfor %}"
   - smtp_smarthost: "{{ ansible_hostname }}"
   - ldapManagerPassword: "imldap"
   - ldapBindDNPassword: "imbinddn"
   - domain: ""
   - karaage_sql_password: "imkaraage"
   - mysql_root_password: "immysql"
   - x509_key_file: "/etc/ssl/private/server.key"
   - x509_cert_file: "/etc/ssl/certs/server.crt"
   - x509_cacert_file: "/etc/ssl/certs/ca.crt"
   - x509_csr_args: ""
   - x509_sign_args: "{{ x509_csr_args }}"
   - x509_common_name: "{{ inventory_hostname }}"
   - apache_user: "{% if ansible_os_family == 'RedHat'  %}apache{% else %}www-data{% endif %}"
