---
-
  hosts: ldap-server
  roles:
#   - easy-rsa-CA
#   - ldapserver
  sudo: true
  vars_files:
   - vars/karaageVars.yml
- 
  hosts: karaage-server
  roles:
#    - easy-rsa-certificate
    - karaage3.1.17
  sudo: true
  vars_files:
   - vars/karaageVars.yml
