--- 
- 
  hosts: openvpn-clients
  remote_user: ec2-user
  roles:
    - { role: syncExports, group_list:['openvpn-clients'], interface_list: ['eth0','tun0'] }
    - nfs-client
  sudo: true
  vars: 
    nfs_server: "vm-118-138-240-224.erc.monash.edu.au"
    openvpn_servers: 
      - vm-118-138-240-224.erc.monash.edu.au
    x509_ca_server: vm-118-138-240-224.erc.monash.edu.au

