---

- hosts: '*'
  roles:
  - etcHosts

#- hosts: 'x509_ca'
#  vars:
#  roles:
#  - { role: easy-rsa-CA }
#
#- hosts: 'OpenVPN-Server'
#  vars:
#    x509_ca_server: "{{ groups['x509_ca'][0] }}"
#  roles:
#  - { role: OpenVPN-Server }
#
#- hosts: 'OpenVPN-Client'
#  vars:
#    x509_ca_server: "{{ groups['x509_ca'][0] }}"
#    openvpn_servers: "{{ groups['OpenVPN-Server'] }}"
#  roles:
#  - { role: OpenVPN-Client }
#
#
#- hosts: 'SubmitHost'
#  roles:
#      - { role: slurm-build, slurm_version: 14.11.0, munge_version: 0.5.11 }

- hosts: ComputeNode
  vars:
    openmpi_version: 1.8.3
    build_node: aciab-comp-0
  roles:

- hosts: 'x509_ca'
  vars:
    openmpi_version: 1.8.3
    build_node: aciab-comp-0
  roles:
  - { role: easy-rsa-CA }

- hosts: 'OpenVPN-Server'
  vars:
    x509_ca_server: "{{ groups['x509_ca'][0] }}"
  roles:
  - { role: OpenVPN-Server }

- hosts: 'OpenVPN-Client'
  vars:
    x509_ca_server: "{{ groups['x509_ca'][0] }}"
    openvpn_servers: "{{ groups['OpenVPN-Server'] }}"
  roles:
  - { role: OpenVPN-Client }

- hosts: ComputeNode
  vars:
    openmpi_version: 1.8.3
    build_node: aciab-comp-0
  roles:
      - { role: slurm-build, slurm_version: 14.11.0, munge_version: 0.5.11 }

- hosts: '*'
  roles:
  - etcHosts

- hosts: ComputeNodes|ManagmentNodes|LoginNodes
  vars:
    slurm_version: 14.11.0
    munge_version: 0.5.11
    slurmqueues: 
      - {name: DEFAULT, group: ComputeNode}
      - {name: batch, group: ComputeNode}
      - {name: gpu, group: ComputeNode}
    slurmctrl: "{{ groups['SubmitHost'][0] }}"
  roles:
      - { role: slurm }
      - { role: test_user }
      - { role: openmpi-build }
      - { role: openmpi-build }

#- hosts: '*'
#  vars:
#    slurm_version: 14.11.0
#    munge_version: 0.5.11
#    slurmqueues: 
#      - {name: DEFAULT, group: ComputeNode}
#      - {name: batch, group: ComputeNode}
#      - {name: gpu, group: ComputeNode}
#    slurmctrl: "{{ groups['SubmitHost'][0] }}"
#  roles:
#      - { role: slurm }
#      - { role: test_user }
#
- hosts: 'karaage'
  vars:
    x509_ca_server: "{{ groups['x509_ca'][0] }}"
    smtp_smarthost: "does_not_exist.massive.org.au"
    ldapDomain: "dc=test,dc=massive,dc=org,dc=au"
    ldapURL: "ldaps://{{ hostvars[groups['ldapserver'][0]]['ansible_fqdn'] }}"
  roles:
  - { role: karaage2.7 }

- hosts: 'ldapserver'
  vars:
    x509_ca_server: "{{ groups['x509_ca'][0] }}"
    ldapDomain: "dc=test,dc=massive,dc=org,dc=au"
  roles:
  - { role: ldapserver }
