--- 
- 
  name: "Building the CA Certificate"
  shell: ' bash -c " cd /etc/easy-rsa/2.0; source ./vars; ./clean-all;  export EASY_RSA=/etc/easy-rsa/2.0; /etc/easy-rsa/2.0/pkitool --initca $* "'
  args:
    creates: /etc/easy-rsa/2.0/keys/ca.crt
  register: initca
  sudo: True

- name: debug
  debug: var=initca

