---
- name: make  dir
  file: path="{{ provision | dirname }}" state=directory mode=755 owner=root
  sudo: true

- name: copy provision template 
  template: src=provision.sh.j2 dest={{ provision }} mode=755 owner=root
  sudo: true

- name: provision cron job 
  cron: name=provision job="/usr/bin/flock -x -n /tmp/provision.lck -c {{ provision }}" user=root minute=*/30 state=present
  sudo: true
