---
- name: "Templating /etc/exports"
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=644
  delegate_to: "{{ nfs_server }}"
  run_once: true
  sudo: true
  notify: "Reload exports"
- name: "Restart the NFS server"
  service: "name=nfs state=restarted"
  delegate_to: "{{ nfs_server }}"
  run_once: true
  sudo: true
