---
- name: "Create exports if necessary"
  file: dest={{ item.src }} state=directory mode=755 owner=root group=root
  sudo: true
  with_items: exportList

- name: "Templating /etc/exports"
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=644
  sudo: true

- name: "Start the Server"
  service: "name=nfs state=restarted"
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "Start the Server"
  service: "name=nfs-kernel-server state=restarted"
  sudo: true
  when: ansible_os_family == "Debian"

- name : "Pause ... clients sometimes have errors"
  command: sleep 60
  notify: "Reload exports"

- name: "Restart the NFS server"
  service: "name=nfs state=restarted"
  delegate_to: "{{ nfs_server }}"
  run_once: true
  sudo: true
