---
-
  name: "Install these yum packages"
  with_items:
    - gcc
    - rsync
    - make
    - tcsh
    - bind-utils
    - openssl-devel
    - nfs-utils
  yum: "name={{ item }} state=present"
  sudo: true
