
- name: install deps in control node
  yum: name={{ item }} state=installed
  sudo: true
  with_items:
    - mysql-server
  when: ansible_os_family == "RedHat"

- name: install deps in control node
  apt: name={{ item }} state=installed
  sudo: true
  with_items:
    - mysql-server
  when: ansible_os_family == "Debian"

- name: "Start the Server"
  service: "name=mysqld enabled=yes state=started"
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "Start the Server"
  service: "name=mysql enabled=yes state=started"
  sudo: true
  when: ansible_os_family == "Debian"

- name: install mysql local root password 
  mysql_user: check_implicit_admin=True login_user=root login_password={{ sqlrootPasswd }} name=root password={{ sqlrootPasswd }} state=present
  sudo: true

- name: configure database slurmdb localhost
  mysql_user: login_user=root login_password="{{ sqlrootPasswd }}" name=slurmdb password="{{ slurmdb_passwd }}" host=localhost priv=*.*:ALL,GRANT state=present
  sudo: true

- name: configure database slurmdb domain 
  mysql_user: login_user=root login_password="{{ sqlrootPasswd }}" name=slurmdb password="{{ slurmdb_passwd }}" host="{{ ansible_hostname }}"."{{ ansible_domain }}" priv=*.*:ALL,GRANT state=present
  sudo: true
