--- 
<<<<<<< HEAD
- 
  args: 
    creates: "/etc/easy-rsa/2.0/keys/{{ ansible_fqdn }}.crt"
  name: "Creating Server certificate"
  shell: " cd /etc/easy-rsa/2.0; source ./vars; export EASY_RSA=\"${EASY_RSA:-.}\"; \"$EASY_RSA/pkitool\"  --server {{ ansible_fqdn }}"
- 
  args: 
    creates: /etc/easy-rsa/2.0/keys/dh512.pem
  name: "Generating Diffie-Hellman Parameters"
  shell: "cd /etc/easy-rsa/2.0; source ./vars; ./build-dh"
=======
- name: "Creating Server certificate"
  shell: "cd /etc/easy-rsa/2.0; source ./vars; export EASY_RSA=\"${EASY_RSA:-.}\"; \"$EASY_RSA/pkitool\" --server {{ server }} creates=/etc/easy-rsa/2.0/keys/{{ server }}.crt"

- name: "Generating Diffie-Hellman Parameters"
  shell: "cd /etc/easy-rsa/2.0; source ./vars; ./build-dh"
  args:
    chdir: /etc/easy-rsa/2.0/keys/
    creates: dh512.pem
>>>>>>> master
