--- 
- name: "Copy the configuration file"
  template: src={{ item }} dest=/etc/easy-rsa/2.0/vars mode=0644 owner=root
  with_first_found:
    - files:
        - vars.j2
        - userConfig
        - defaultConfig
      paths:
        - ../../easy-rsa-CA/templates
        - /mnt/nectar-nfs/root/ansible-config-root/ansible_cluster_in_a_box/roles/easy-rsa-CA/files

