---

- name: create slurm group
  group: name=slurm system=yes gid=497
  sudo: true

- name: create slurm user
  user: name=slurm group=slurm system=yes createhome=no uid=497
  sudo: true

- name: make sure slurm conf dir exists
  file: dest=/etc/slurm state=directory
  sudo: true

- name: create data directory
  file: path="{{ slurmdatadir }}" state=directory owner=slurm group=slurm mode=755 
  sudo: true

- name: create log directory
  shell: mkdir -p {{ slurmddebug.log | dirname }}; chown slurm:slurm {{ slurmddebug.log | dirname }} 
  args:
    creates: "{{ slurmddebug.log | dirname }}"
  sudo: true
  when: slurmddebug is defined and slurmddebug.log

- name: copy rpms
  copy: src=/tmp/rpmbuild dest=/tmp
  sudo: true

- name: install munge rpms
  shell: "rpm --install /tmp/rpmbuild/RPMS/x86_64/munge*{{ munge_version }}*rpm"
  sudo: true
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: install deps
  apt: name={{ item }} state=installed update_cache=yes
  sudo: true
  with_items:
    - gcc
    - wget
    - libssl-dev
    - libpam0g-dev
    - libbz2-dev
    - make
    - alien
  when: ansible_os_family == "Debian"

- include: installMungeFromSource.yml
  when: ansible_os_family == "Debian"

- name: install munge key
  template: src=munge_key.j2 dest=/etc/munge/munge.key owner=munge mode=600
  sudo: true
  notify: restart munge

- name: install perl
  yum: name={{ item }} state=latest
  with_items:
    - perl
    - perl-DBI
  sudo: true
  when: ansible_os_family == "RedHat"

- name: install perl
  apt: name={{ item }} state=latest
  with_items:
    - perl
    - libdbi-perl
  sudo: true
  when: ansible_os_family == "Debian"


- include: installSlurmFromSource.yml
  when: ansible_os_family == "Debian"

- name: install slurm rpms
  shell: "rpm --install /tmp/rpmbuild/RPMS/x86_64/slurm*{{ slurm_version }}*rpm"
  sudo: true
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: install slurm.conf
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf
  sudo: true
  when: slurm_use_vpn==False

- name: install slurm.conf
  template: src=slurm-vpn.conf.j2 dest=/etc/slurm/slurm.conf
  sudo: true
  when: slurm_use_vpn==True


- name: start munge
  service: name=munge state=started
  sudo: true

- name: start slurm
  service: name=slurm state=started
  sudo: true
