---
-
  name: Adding default ppolicy schema
  shell: ldapadd -Y EXTERNAL -H ldapi:/// < /etc/ldap/schema/ppolicy.ldif
-
  name: templating tls settings
  template: src=tls_settings.ldif.j2 dest=/tmp/tls_settings.ldif mode=600
-
  name: initialise server ssl
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// < /tmp/tls_settings.ldif
  sudo: true
-
  name: templating ldap.conf
  template: src=ldap.conf.j2 dest=/etc/ldap/ldap.conf mode=600
