- name: get slurm
  shell: wget https://cvl.massive.org.au/slurm-{{ slurm_version }}.tar.bz2
#  shell: wget http://www.schedmd.com/download/archive/slurm-{{ slurm_version }}.tar.bz2
  args:
    chdir: /tmp
    creates: /tmp/slurm-{{ slurm_version }}.tar.bz2

- name: untar slurm
  shell: tar jxf /tmp/slurm-{{ slurm_version }}.tar.bz2
  args:
    chdir: /tmp

- name: build slurm
  shell: ./configure --prefix={{ slurm_dir }} --with-munge={{ munge_dir }} && make
  args:
    chdir: /tmp/slurm-{{ slurm_version }}
    creates: /tmp/slurm-{{ slurm_version }}/src/srun/srun

- name: install slurm
  shell: make install
  sudo: true
  args:
    chdir: /tmp/slurm-{{ slurm_version }}
    creates: "{{ slurm_dir }}/bin/srun"

- name: copy init script
  template: dest=/etc/init.d/slurm src=slurm.initd.j2  mode=755
  sudo: true   

- name: "copy ldap.conf RedHat"
  template: src=ldap.conf.j2 dest=/etc/openldap/ldap.conf owner=root group=root mode=644
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "copy ldap.conf Debian"
  template: src=ldap.conf.j2 dest=/etc/ldap/ldap.conf owner=root group=root mode=644
  sudo: true
  when: ansible_os_family == "Debian"



