- name: clean up system installation
  shell: rpm -e munge-libs slurm-munge munge slurm-plugins munge-devel slurm slurm-slurmdbd slurm-perlapi slurm-devel slurm-pam_slurm slurm-sjstat slurm-perlapi slurm-pam_slurm slurm-slurmdb-direct slurm-torque slurm-sjobexit
  ignore_errors: true
  sudo: true
  when: ansible_os_family == 'RedHat'

- name: get munge
  shell: wget https://munge.googlecode.com/files/munge-{{ munge_version }}.tar.bz2
  args:
    chdir: /tmp
    creates: /tmp/munge-{{ munge_version }}.tar.bz2

- name: untar munge
  shell: tar jxf munge-{{ munge_version }}.tar.bz2
  args:
    chdir: /tmp
    creates: /tmp/munge-{{ munge_version }}

- name: build munge
  shell: ./configure --prefix={{ munge_dir }} && make
  args:
    chdir: /tmp/munge-{{ munge_version }}
    creates: /tmp/munge-{{ munge_version }}/src/munge/munge

- name: install munge
  shell: make install
  sudo: true
  args:
    chdir: /tmp/munge-{{ munge_version }}
    creates: "{{ munge_dir }}/bin/munge"

- name: copy init script
  template: dest=/etc/init.d/munge src=munge.initd.j2 mode=755
  sudo: true
