---

-
 name: "Installing Apache"
 yum: name={{ item }} state=latest
 with_items:
  - mod_ssl
  - mod_wsgi 
  - openssl
  - httpd
  - httpd-devel
-
 name: Setting httpd.conf
 replace: dest=/etc/httpd/conf/httpd.conf regexp="^#ServerName www.example.com:80" replace="ServerName {{ ansible_fqdn }}"
-
 name: Setting ssl.conf
 lineinfile: dest=/etc/httpd/conf.d/ssl.conf regexp="{{ item.regexp }}" line="{{ item.line }}" backrefs=yes
 with_items:
  - { regexp : "^SSLCertificateFile", line : "SSLCertificateFile {{ x509_cert_file }}" }
  - { regexp : "SSLCertificateKeyFile", line : "SSLCertificateKeyFile {{ x509_key_file }}" }
  - { regexp : "SSLCACertificateFile", line : "SSLCACertificateFile {{ x509_cacert_file }}" }
-
 name: Templating wsgi.conf
 template: src=wsgi.conf.j2 dest=/etc/httpd/conf.d/wsgi.conf owner=root group=root
-
 name: Restarting Apache
 service: name=httpd state=restarted
