---
-
 name: "Install Apache2"
 apt: name={{ item }} state=present
 with_items:
  - apache2
  - apache2-dev
-
 name: "Setting default site"
 lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="#ServerName" line="ServerName {{ ansible_nodename }}" backrefs=yes
-
 name: "Setting default-ssl site"
 lineinfile: dest=/etc/apache2/sites-available/default-ssl.conf  regexp="{{ item.regexp }}" line="{{ item.line }}" backrefs=yes
 with_items:
  - { regexp : "^\\s+SSLCertificateFile", line : "		SSLCertificateFile {{ x509_cert_file }}" }
  - { regexp : "SSLCertificateKeyFile", line : "		SSLCertificateKeyFile {{ x509_key_file }}" }
  - { regexp : "SSLCACertificateFile", line : "		SSLCACertificateFile {{ x509_cacert_file }}" }
-
 name: "Enable ssl module"
 apache2_module: state=present name=ssl

-
 name: "Enable default-ssl site"
 shell: a2ensite default-ssl

-
 name: "Restarting Apache2"
 service: name=apache2 state=restarted
