---
-
 name: "Installing prerequisites"
 apt: name={{ item }} update_cache=yes
 with_items:
  - libxml2-dev
  - libxslt1-dev
  - python-lxml
  - libcrack2-dev
  - csstidy
  - ldap-utils
  - python-cracklib
  - git
-
 name: "Getting Karaage from Github"
 git: repo="https://github.com/monash-merc/karaage.git" dest="/root/karaage3.1.7"
-
 name: "Installing Karaage Dependencies"
 pip: name={{ item }} extra_args="--upgrade"
 with_items:
  - six
  - MySQL-python
  - mincss
  - slimit
  - ply
-
 name: "Restrict Django version to 1.7.8"
 replace: dest=/root/karaage3.1.7/setup.py regexp="Django >= 1.7" replace="Django == 1.7.8"
-
 name: "Installing Karaage from source"
 shell: python setup.py install 
 args:
  chdir: /root/karaage3.1.7
  creates: /root/karaage3.1.7/build/bdist.linux-x86_64
-
 name: "Templating Karaage settings"
 template: src=settings.py.j2 dest=/etc/karaage3/settings.py owner=root group=www-data mode=0640
-
 name: "Creating karaage3 in /var/log"
 file: path=/var/log/karaage3 state=directory owner=www-data group=www-data mode=0755 
-
 name: "Creating karaage3 in /var/lib"
 file: path=/var/lib/karaage3 state=directory owner=root group=www-data mode=0775
-
 name: "Change permissions for /var/www"
 file: path=/var/www state=directory owner=root group=www-data mode=0775
-
 name: "enabling Karaage configuration"
 shell: a2enconf karaage3-wsgi
-
 name: "Installing other packages"
 apt: name={{ item }} update_cache=yes
 with_items:
  - python-kgusage
  - karaage-cluster-tools
  - karaage3-celery
-
 name: "Set Secret Key"
 lineinfile: dest=/etc/karaage3/settings.py regexp="SECRET_KEY = ''" line="SECRET_KEY = 'imkaraage'" state=present
-
 name: " Create DB tables"
 shell: kg-manage migrate 
-
 name: "Restarting Celery"
 service: name=karaage3-celery state=restarted
-
 name: "Reloading apache"
 service: name=apache2 state=reloaded
