---
 - include: prerequisitesDebian.yml
   when: ansible_os_family == "Debian"
 - include: apacheDebian.yml
   when: ansible_os_family == "Debian"
 - include: apacheRedHat.yml
   when: ansible_os_family == 'RedHat'
 - include: karaage.yml
