---

 - name: "Copying the ldap ca cert file"
   template: src="files/{{ ldap_TLSCARoot }}" dest="{{ apache_config }}/ssl/certs/ldap_ca.cert.pem" mode=0644
   sudo: true
   when: apache_cert_file is defined

 - include: prerequisitesDebian.yml
   when: ansible_os_family == "Debian"
 - include: karaage.yml
