---
- 
 name: "Installing MySQL Debian"
 apt: name="{{ item }}" update_cache=yes cache_valid_time=3600 state=present
 with_items:
  - python
  - python-dev
  - libmysqlclient-dev
  - python-pip
  - libapache2-mod-wsgi
  - python-mysql.connector
  - mysql-server
  - python-mysqldb
 when: ansible_os_family == "Debian"
-
 name: Installing MySQL RedHat
 yum: name="{{ item }}" state=latest
 with_items:
  - python
  - python-devel
  - mysql-devel
  - mysql-libs
  - MySQL-python
  - mysql-server
 when: ansible_os_family == "RedHat"
- 
 name: "Starting MySQL"
 service: name=mysql state=started enabled=true
 when: ansible_os_family == "Debian"

- 
 name: "Starting MySQL"
 service: name=mysqld state=started enabled=true
 when: ansible_os_family == "RedHat"
-
 name: "Templating karaage.cnf"
 template: src="karaage.cnf.j2" dest=/etc/mysql/conf.d/karaage.cnf owner=root group=root
 when: ansible_os_family == "Debian"

-
 name: "Adding root"
 sudo: true
 mysql_user: name=root host="{{ item }}" password="{{ mysql_root_password }}" login_user=root login_password="{{ mysql_root_password }}" check_implicit_admin=yes priv="*.*:ALL,GRANT"
 with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost
-
 name: Setting mysql global variables
 mysql_variables: variable={{ item.var }} value={{ item.val }} login_user=root login_password="{{ mysql_root_password }}"
 with_items:
  - { var : 'character_set_server', val : 'utf8' }
  - { var : 'storage_engine', val : 'innodb' }
  - { var : 'sql_mode', val : 'STRICT_ALL_TABLES' }
 when: ansible_os_family == "RedHat"
-
 name: "Editing my.cnf"
 lineinfile: dest=/etc/my.cnf  line="{{ item }}"
 with_items:
  - '[client]'
  - 'default-character-set = utf8'
 when: ansible_os_family == "RedHat"
-
 name: "Adding Karaage Database"
 mysql_db: name=karaage state=present login_user=root login_password={{ mysql_root_password }} 
-
 name: "Giving priviliges to karaage user"
 mysql_user: name=karaage password={{ karaage_sql_password }} login_user=root login_password={{ mysql_root_password }} priv=karaage.*:ALL state=present

- 
 name: "Starting MySQL"
 service: name=mysql state=restarted
 when: ansible_os_family == "Debian"
-
 name: "Starting MySQL"
 service: name=mysqld state=restarted
 when: ansible_os_family == "RedHat"
