--- 
- 
  delegate_to: "vm-118-138-240-224.erc.monash.edu.au"
  name: "Check if certificate exist"
  register: cert
  stat: "path=/etc/easy-rsa/2.0/keys/{{ client }}.crt"
- 
  delegate_to: "vm-118-138-240-224.erc.monash.edu.au"
  name: "Creating Client certificate"
  shell: ' cd /etc/easy-rsa/2.0; source ./vars; export EASY_RSA="${EASY_RSA:-.}"; "$EASY_RSA"/pkitool --csr {{ client }} ;"$EASY_RSA"/pkitool --sign {{ client }}'

