- name: "restart sshd"
  service: name=sshd state=restarted
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "restart ssh"
  service: name=ssh state=restarted
  sudo: true
  when: ansible_os_family == "Debian"
