---
- include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yaml"

- name: copy rpms
  copy: dest=/tmp/ src=lustre-install/{{ item }}
  with_items:
    "{{ lustre_pkgs }}"

#- name: install rpms
#  yum: name="/tmp/{{ item }}"
#  sudo: true
#  with_items: "{{ lustre_pkgs }}"

- name: install rpms
  yum: name=/tmp/lustre-client-modules-2.7.0-3.10.0_229.14.1.el7.x86_64.x86_64.rpm
  sudo: true

- name: install rpms
  yum: name=/tmp/lustre-client-2.7.0-3.10.0_229.14.1.el7.x86_64.x86_64.rpm
  sudo: true

  
- name: "Mount lustre filesystems"
  mount: name="{{ item.mntpt }}" src="{{ item.servers }}"/"{{ item.src }}" state="mounted" fstype="lustre" opts="_netdev,flock" 
  sudo: true
  with_items: "{{ mntlist }}"
