--- 
- name: "Mounting NFS mounts"
  mount: "name={{ nfsClientDestDir }} src={{ nfs_server }}:{{ nfsClientSrcDir }} fstype={{ nfs_type }} opts={{ nfs_options }} state=mounted"
  notify: "restart authentication"
  notify: "restart idmap"
  sudo: true 

  
