--- 
- 
  mount: "name={{ item.0 }} src={{ nfs_server }}:{{ item.1 }} fstype={{ nfs_type }} opts={{ nfs_options }} state=mounted"
  name: "Mounting NFS mounts"
  with_together: 
    - destDir
    - srcDir
  notify: "restart authentication"
  notify: "restart idmap"
  sudo: true 

  
