--- 
-
  name: "Get the NFS Network"
  setup: 
  register: nfsServer
  run_once: true
  delegate_to: "{{ nfs_server }}"
- 
  mount: "name={{ item.name }} src={{ nfsServer['ansible_facts']['ansible_'+item.interface]['ipv4']['address'] }}:{{ item.src }} fstype={{ item.fstype }} opts={{ item.opts }} state=mounted"
  name: "Mounting NFS mounts"
  with_items: exportList 
  notify: "restart authentication"
  notify: "restart idmap"
  sudo: true 
