--- 
- 
  mount: "name={{ item.0 }} src={{ nfs_server }}:{{ item.1 }} fstype=nfs opts=vers=3,noatime,rsize=16384,wsize=16384,hard,intr,tcp,nolock state=mounted"
  name: "Mounting NFS mounts"
  with_together: 
    - destDir
    - srcDir

