--- 
- name: "Mounting NFS mounts"
  mount: name={{ item.name }} src={{ hostvars[nfs_server]['ansible_'+item.interface]['ipv4']['address'] }}:{{ item.src }} fstype={{ item.fstype }} opts={{ item.opts }} state=mounted
  with_items: exportList 
  notify: "restart authentication"
  notify: "restart idmap"
  sudo: true 
  when: exportList is defined 
