---
ldapDomain: "monash.edu.au" 
ldapDn: "cn=ldapbind,cn=users,dc=monash,dc=edu,dc=au" 
ldapPassword: "secret"
ldapBase: "cn=users,dc=monash,dc=edu,dc=au"
ldapUserClass: "user"
ldapUserHomeDirectory: "unixHomeDirectory"
ldapUserPricipal: "userPrincipalName"
ldapGroupBase: "ou=groups,dc=monash,dc=edu,dc=au"
tlsCaCertDirectory: "/etc/openldap/certs"
tlsCaCertFile: "ca.pem"
ldapCaCertFileSource: "/etc/openldap"
