---
-
 name: Install yum packages
 yum: name={{ item }} state=present
 with_items:
  - gcc
  - openssl-devel
  - db4-devel
-
 name: Download Openldap
 get_url: url=ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-2.4.40.tgz dest=/tmp/openldap-2.4.40.tgz
-
 name: Untar OpenLdap
 shell: tar xvf openldap-2.4.40.tgz chdir=/tmp creates=/tmp/openldap-2.4.40
-
 name: Configure Openldap
 shell: ./configure --with-tls=openssl --with-cyrus-sasl chdir=/tmp/openldap-2.4.40 creates=/tmp/openldap-2.4.40/config.log
-
 name: Install Openldap
 shell: make -j 4; make install
 args:
  chdir: /tmp/openldap-2.4.40/
  creates: /usr/local/libexec/slapd 
-
 name: Start the server
 shell: /usr/local/libexec/slapd
 ignore_errors: yes
